# Generated by Django 4.0.2 on 2022-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
