# Generated by Django 4.0.2 on 2022-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uploadfile_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
